### ISSUE TITLE
Use custom units & places in Soulver action?

### ISSUE THREAD

**Issue by Nigelw** [Ptujec/LaunchBar#13]
Is it possible for the Soulver action to recognize custom units & places set up within Soulver?

For example, I've setup custom units so I can type `5 c in f` in Soulver instead of `5 celsius in fahrenheit`, but these units aren't recognized by this launchbar action. Is that possible at all, or does it depend entirely on SoulverCLI to recognize custom units you enter in Settings?

**Comment by zcohan** [comment]
Actually even the SoulverCLI doesn't load the custom units at the moment, so this won't be possible yet.

**Comment by Ptujec** [comment]
Yes, there are certain limitations to the CLI. One I run into was that it doesn't support German while the app itself does.

**Comment by Nigelw** [comment]
Thanks for the response! I’ll ask Soulver support whether they plan to add support for these things in the CLI tool.

**Comment by zcohan** [comment]
That's me 🙂. I'm thinking about the best way to do this…

**Comment by Nigelw** [comment]
Oh cool! Thanks Zac 🙂
