### ISSUE TITLE
Action Troubleshoot - e.g. File-Action

### ISSUE THREAD

**Issue by dkzsys** [Ptujec/LaunchBar#14]
Hi Christian, 

I'd to seek some assistance on troubleshooting the installation of these Action files you shared please.

I tried to install File-Action (https://github.com/Ptujec/LaunchBar/tree/master/File-Actions). I managed to load the .lbaction, and it's available in Action Editor. However, it's not available in Action Index. See below screenshots for reference.
![image](https://user-images.githubusercontent.com/39715311/212187207-8d6f255c-1a36-4072-8e99-22c2c49b2bbe.png)

![image](https://user-images.githubusercontent.com/39715311/212187328-7720fb27-0b3f-42b8-a5b7-35e2f12bab71.png)

This is what LB shows when I tried to action "Filter".
![image](https://user-images.githubusercontent.com/39715311/212187979-4b8f48e7-e52a-4390-a08b-fabfba8d1919.png)

I'm relatively new to "Action", and have a brief understanding on how the plist, scripts are defined. But couldn't find anything unusual for the File-Action script.

Any idea on how to troubleshoot this? 

Thanks.

**Comment by Ptujec** [comment]
Hi! 
I see one of the actions showing up at the bottom of your last screenshot. But its in German, because there is a missing file, which makes the action default to German. Sorry. I fixed that just now and pushed an update. 
 
The actions should show up after that. But they still might be lower in the list. This is by design. Here is why and what you can do for it to show up on top: https://youtu.be/CslnF0BPma0?t=69

**Comment by dkzsys** [comment]
Thank you for the prompt response, Christian. 

The updated Actions works, after reload and restart LB:)
![image](https://user-images.githubusercontent.com/39715311/212197867-772f5dd2-c869-4794-a9c8-ffd8a33e5118.png)
 
I am facing a different issue using "Filter by Type" - it's complaining about "undefined" object definition in the script. Any idea for this please?
![image](https://user-images.githubusercontent.com/39715311/212197697-15539767-2a8b-482f-ab16-61eed0dedf3e.png)

**Comment by dkzsys** [comment]
I found this closed issue: https://github.com/Ptujec/LaunchBar/issues/4

"~/Library/Application Support/LaunchBar/Action Support/ptujec.LaunchBar.action.FilterByType/Preferences.plist" does not exist.
![image](https://user-images.githubusercontent.com/39715311/212198867-f97f8fc6-a979-4a65-9815-a677360ea311.png)

What do I need to do to resolve the permission issue, if I understand it correctly?

**Comment by Ptujec** [comment]
Yes, this is the same issue. Still can't reproduce it here. I tried something to fix it. But it may also just not show any results.

**Comment by dkzsys** [comment]
The update is working like a charm! Thank you, Christian. 
![image](https://user-images.githubusercontent.com/39715311/212203377-4899391e-4200-4a3a-bf1b-b32015db8a6b.png)

All other actions in the package are working as expected. Pls feel free to close this issue. Cheers.
