### ISSUE TITLE
Notifications Action - Not available in Action Index

### ISSUE THREAD

**Issue by dkzsys** [Ptujec/LaunchBar#15]
Hi Christian,

I'm trying to install the Notifications action pack - https://github.com/Ptujec/LaunchBar/tree/master/Notifications

I have managed to load them into Action Editor; but they are not showing up in Action Index. I've checked the Resources directory and confirmed en.lproj was there, I have also manually selected "English" for the Locolizations in Action Editor.

![image](https://user-images.githubusercontent.com/39715311/212200487-b2a2bace-6392-490a-96c7-8b5b84fdb930.png)

![image](https://user-images.githubusercontent.com/39715311/212200502-cfcb087a-8bca-4e15-a286-12f37dffb412.png)

Some help is appreciated!

**Comment by Ptujec** [comment]
They probably don't show up because they require Ventura. Sorry.

**Comment by dkzsys** [comment]
No probs at all. I've been putting off the upgrade to Ventura lately. Maybe it's time now:) 

I have manually downloaded the version from Jan 2022 - https://github.com/Ptujec/LaunchBar/tree/0a4277f3bcd2512735be61a5326910097b4bb9c6/Notifications

Still unable to load into Action Index. Is this expected? Is upgrade the only option now?

**Comment by Ptujec** [comment]
Yes, this is expected. They don't show up because they would not work. There is a flag in the action. You would need a version before Oct 25 … but I don't have them handy. 
You can see the history of changes here: https://github.com/Ptujec/LaunchBar/commits/master/Notifications

**Comment by dkzsys** [comment]
Let me plan the upgrade and retry after that. Thanks.
