### ISSUE TITLE
Mastodon: Error: No localization table named "default" found

### ISSUE THREAD

**Issue by defulmere** [Ptujec/LaunchBar#16]
Testing `Mastodon Search.lbaction` on Ventura 13.1, invoking the action results in an error message "Error: No localization table named default found.":

![image](https://user-images.githubusercontent.com/104225/212978475-aab2c81d-2fc4-458c-a97a-7051a01618d7.jpeg)

**Comment by Ptujec** [comment]
Sorry! Should be fixed now.
