### ISSUE TITLE
Can't visit profiles on configured instance

### ISSUE THREAD

**Issue by defulmere** [Ptujec/LaunchBar#18]
Me again :)

If you search for a profile that's on the same instance configured in the action settings, you're directed to domain.com/@user@domain.com and the profile never loads.

For example:

- My instance is opalstack.social. 
- If I search for my own name and hit enter on the result, I'm taken to https://opalstack.social/@sean@opalstack.social and the page spins forever.
- If I search for a user on another instance, eg Eugen Rochko, I'm taken to https://opalstack.social/@Gargron@mastodon.social which loads correctly.

Not sure if this is a bug in Mastodon or what, but if your action would recognize "local" searches and omit the instance from the end of the URL like "https://opalstack.social/@sean" then would solve this.

**Comment by Ptujec** [comment]
Good catch! Should be fixed now.
