### ISSUE TITLE
Cannot add Developer Token - receive an error on launch

### ISSUE THREAD

**Issue by andrewcanion** [Ptujec/LaunchBar#2]
When I invoke YNAB-Add Transaction and attempt to choose my budget, I receive the following system error: `Cannot add Developer Token` `TypeError: undefined is not an object (evaluating 'bData.data.data.budgets') (line 601).`.

I have not been prompted to input my Developer Code.

**Comment by Ptujec** [comment]
Thank you Andrew for reporting. You probably set an invalid token. I updated the action to handles this a bit better. You will now be promted to set the token again.
