### ISSUE TITLE
Zotero type/field ids aren't stable

### ISSUE THREAD

**Issue by dstillman** [Ptujec/LaunchBar#23]
I noticed you hard-coded ids in the action, but those actually aren't stable as of a few years ago. You'd want to query those from `itemTypes`/`fields`/`creatorTypes` in the DB. As written, this might not work properly for people who started using Zotero at a different time from you.

(An upcoming version of Zotero will add a local HTTP-based API that works the same as the web API, so you should be able to switch to that when it comes out and avoid database queries — and the database copy — completely.)

**Comment by Ptujec** [comment]
Thank you for your feedback, Dan! 
If I understand you correctly I can not assume that "2" is always the itemTypeID for a "book"? So I have to go by the name because for newer users the id could be a different one?

Looking forward to the local HTTP-based API. Thanks for all the hard work.

**Comment by dstillman** [comment]
> If I understand you correctly I can not assume that "2" is always the itemTypeID for a "book"?

Correct

> So I have to go by the name because for newer users the id could be a different one?

Well, you have to get the ids from those tables, assign them to variables, and then use those in place of the integers.

**Comment by Ptujec** [comment]
I think I fixed it. Thanks for letting me know!
