### ISSUE TITLE
Zotero Search only works with Zotero default Data Directory Location

### ISSUE THREAD

**Issue by jpcirrus** [Ptujec/LaunchBar#25]
Firstly, many thanks for all your LB Actions.

When Zotero is configured to use a custom Data Directory Location (see image below) it does not work as all the script paths are hardcoded to the Zotero default.

<img width="805" alt="image" src="https://github.com/Ptujec/LaunchBar/assets/39587/86bb964e-2ebd-40c9-809e-ecc27dddc8f2">

**Comment by Ptujec** [comment]
Thx for reporting @jpcirrus

**Comment by jpcirrus** [comment]
Many thanks for the quick fix. Works great.
