### ISSUE TITLE
Menu Bar Action not displayed up in Launchbar 

### ISSUE THREAD

**Issue by onedrop2000** [Ptujec/LaunchBar#26]
Hi there,
I just installed your menu-bar action for launchbar, but it doesnt show up in launchbar.

Any ideas?

Thanks + regards,
Johannes

**Comment by Ptujec** [comment]
Do you have Finbar installed? The action requires the app to work.

**Comment by onedrop2000** [comment]
Hi,

Well actually not :) thanks for the hint. I just installed it, will 
check it out. It works now.

An by the way, thanks for sharing your Launchbar Actions. :)

Kind Regards from Austria,
Johannes

Onedrop Multimedia Agentur
Johannes Strickner
Pongartgasse 8, 6850 Dornbirn
Vorarlberg, Austria
T: +43 650 8220010
www.onedrop.co
