### ISSUE TITLE
Problem with Music Song Info

### ISSUE THREAD

**Issue by verboEse** [Ptujec/LaunchBar#27]
Hi,

I got an error with "Musik - Song Info":
`Der Vorgang konnte nicht abgeschlossen werden. /Users/verboese/Library/Application Support/LaunchBar/Actions/Music - Song Info.lbaction/Contents/Scripts/default.applescript:1535:1539: execution error: „Music“ hat einen Fehler erhalten: Die Typen der Deskriptoren passen nicht. (-10001)
`
This occurs for each song I play.

**Comment by verboEse** [comment]
Hallo.

Ja, Sonoma auf einem Intel-MacBook.

**Comment by Ptujec** [comment]
Ok, ich schau es mir an, wenn ich update. Im Moment kann ich leider noch nicht. Evtl. kannst du es fixen, wenn du das AS im Skripteditor öffnest und versuchst da laufen zu lassen.

**Comment by Ptujec** [comment]
Sollte jetzt gefixt sein. Der Grund für das Problem war das Apple in Sonoma "loved" zu "favorited" geändert hat.
