### ISSUE TITLE
Launchbar vs alfred

### ISSUE THREAD

**Issue by Rhydderch** [Ptujec/LaunchBar#28]
Hello,

First of all sorry to use this issue as a way to ask you this question but I am really curious about your use of launchbar. You really seem to be a power user. It is the first time I hear about it. Is it similar/better to Alfred for mac?

I mainly code, research, write (I am a PhD student), and use obsidian every day.

**Comment by Ptujec** [comment]
I answered here: https://github.com/Ptujec/LaunchBar/discussions/29
