### ISSUE TITLE
Typo (Buget)

### ISSUE THREAD

**Issue by andrewcanion** [Ptujec/LaunchBar#3]
Thanks for fixing my last bug - it's working now.

Thought I'd let you know there is a typo in the "Budget Set" notification upon setting the budget - you have it as "Buget". ;-)

Thanks for the great Action!
![CleanShot 2021-09-14 at 12 33 00](https://user-images.githubusercontent.com/33217625/133195603-6e550a2a-596f-4fb3-9b92-aa8da0d13770.png)

**Comment by Ptujec** [comment]
Thanks for reporting.
