### ISSUE TITLE
Cannot view scratchpad contents via the Gedankensalat action

### ISSUE THREAD

**Issue by jnouwen** [Ptujec/LaunchBar#37]
**LaunchBar 6.20.1
Gedankensalat version 2 (from 3 weeks ago)**

The Gedankensalat action appears to not currently have a way to display the contents of the scratchpad file. The readme for the action doesn't state _how_ to view the contents, just that you can (though looking at the code, it seems clear that merely hitting return is how it should work):
>Later, you can go back and decide what to do with it

Things that do work fine:
* creating a new file via the action
* selecting a different file via the action
* adding new items to any of the selected files (created new or pre-existing)

It's just viewing the contents of that file doesn't work. When selecting the action in LaunchBar, hitting return merely changes the action to add a label indicating it's a custom action:

![Example of what LaunchBar "does" after hitting return](https://github.com/user-attachments/assets/326ec3a6-f220-4250-9676-a39f30e1790d)

I would've stepped through the code to see where, specifically, in `show()` it's failing but I'm not actually sure how to attach a debugger to scripts run by a LaunchBar action 🙂

**Comment by Ptujec** [comment]
It's probably related to how I split things up to create the title and subtitles. It is expecting a certain date format. I'll fix that asap 🤦🏻‍♂️

**Comment by Ptujec** [comment]
Thanks for reporting this and even attempting to fix it in my messy code! 
I use this to read the logs for my actions: `log stream --predicate '(processImagePath CONTAINS "LaunchBar") AND (eventMessage CONTAINS "ptujec.LaunchBar.action")' --style compact`. I started using somewhat more proper logging just recently, though, so that would not have done much.
