### ISSUE TITLE
Error running Filter by Type

### ISSUE THREAD

**Issue by latca** [Ptujec/LaunchBar#4]
When passing a folder to Filter by Type a error is thrown on line 74.
![image](https://user-images.githubusercontent.com/353804/133827725-c2f9ec0e-1ed0-4175-a9c0-0496a2b573d5.png)

**Comment by Ptujec** [comment]
Hhm, I can't reproduce the error. Can you give more details? What OS version are you on?

**Comment by Ptujec** [comment]
It kind of sounds like an issue with permissions. typeDeclarations normally should not be undefined. This is the collected type data from /System/Library/CoreServices/CoreTypes.bundle/Contents/Info.plist and Application info plists. It stores the extensions sorted by type in ~/Library/Application Support/LaunchBar/Action Support/ptujec.LaunchBar.action.FilterByType/Preferences.plist
Does this file exsist?
